-- Default to not using Nerd Font icons unless overridden
vim.g.use_nerd_icons = false

-- Use Nerd Font icons if on Mac or explicitly enabled
if vim.fn.has "mac" == 1 or vim.g.use_nerd_icons then
  return {
    kind = {
      Text = "󰉿 ",          -- Text (nf-md-text)
      Method = "󰆧 ",        -- Method (nf-md-function_variant, gear-like)
      Function = "󰊕 ",      -- Function (nf-md-function)
      Constructor = "󰢟 ",   -- Constructor (nf-md-hammer)
      Field = "󰄷 ",         -- Field (nf-md-sign_direction)
      Variable = "󰀫 ",      -- Variable (nf-md-variable)
      Class = "󰠱 ",         -- Class (nf-md-class)
      Interface = "󰨰 ",     -- Interface (nf-md-interface)
      Module = "󰏗 ",        -- Module (nf-md-package)
      Property = "󰜢 ",      -- Property (nf-md-pin)
      Unit = "󰑭 ",          -- Unit (nf-md-ruler)
      Value = "󰎠 ",         -- Value (nf-md-numeric)
      Enum = "󰖀 ",          -- Enum (nf-md-format_list_numbered)
      Keyword = "󰉾 ",       -- Keyword (nf-md-key)
      Snippet = "󰘍 ",       -- Snippet (nf-md-content_cut)
      Color = "󰏘 ",         -- Color (nf-md-palette)
      File = "󰈔 ",          -- File (nf-md-file)
      Reference = "󰌷 ",     -- Reference (nf-md-link_variant)
      Folder = "󰉋 ",        -- Folder (nf-md-folder)
      EnumMember = "󰖂 ",    -- EnumMember (nf-md-format_list_numbered_rtl)
      Constant = "󰏿 ",      -- Constant (nf-md-lock)
      Struct = "󰅳 ",        -- Struct (nf-md-table)
      Event = "󰈸 ",         -- Event (nf-md-flash)
      Operator = "󰆕 ",      -- Operator (nf-md-plus)
      TypeParameter = "󰗀 ", -- TypeParameter (nf-md-format_text_variant)
      Misc = "󰺶 ",          -- Misc (nf-md-star)
    },
    type = {
      Array = "󰅪 ",         -- Array (nf-md-brackets)
      Number = "󰎠 ",        -- Number (nf-md-numeric)
      String = "󰉿 ",        -- String (nf-md-text)
      Boolean = "󰝤 ",       -- Boolean (nf-md-toggle_switch)
      Object = "󰏗 ",        -- Object (nf-md-package)
    },
    documents = {
      File = "󰈔 ",          -- File (nf-md-file)
      Files = "󰈕 ",         -- Files (nf-md-file_multiple)
      Folder = "󰉋 ",        -- Folder (nf-md-folder)
      OpenFolder = "󰝰 ",    -- OpenFolder (nf-md-folder_open)
    },
    git = {
      Add = "󰐗 ",           -- Add (nf-md-plus_circle)
      Mod = "󰏬 ",           -- Mod (nf-md-pencil)
      Remove = "󰍴 ",        -- Remove (nf-md-minus_circle)
      Ignore = "󰈉 ",        -- Ignore (nf-md-eye_off)
      Rename = "󰑕 ",        -- Rename (nf-md-arrow_right_bold)
      Diff = "󰕧 ",          -- Diff (nf-md-compare)
      Repo = "󰳾 ",          -- Repo (nf-md-git)
      Octoface = "󰊢 ",      -- Octoface (nf-md-github)
      Branch = "󰘬 ",        -- Branch (nf-md-source_branch)
    },
    ui = {
      ArrowClosed = "󰅂 ",   -- Closed chevron (nf-md-chevron_right)
      ArrowOpen = "󰅀 ",     -- Open chevron (nf-md-chevron_down)
      Lock = "󰍁 ",          -- Lock (nf-md-lock)
      Circle = "󰝤 ",        -- Small circle (nf-md-toggle_switch)
      BigCircle = "󰺖 ",     -- Larger circle (nf-md-circle)
      BigUnfilledCircle = "󰺕 ", -- Outline circle (nf-md-circle_outline)
      Close = "󰅖 ",         -- Cross close (nf-md-close)
      NewFile = "󰝒 ",       -- New file plus (nf-md-file_plus)
      Search = "󰍉 ",        -- Search magnifier (nf-md-magnify)
      Lightbulb = "󰌵 ",     -- Lightbulb (nf-md-lightbulb)
      Project = "󰅱 ",       -- Project (nf-md-code_braces)
      Dashboard = "󰕮 ",     -- Dashboard (nf-md-view_dashboard)
      History = "󰚰 ",       -- History (nf-md-history)
      Comment = "󰅺 ",       -- Comment (nf-md-comment)
      Bug = "󰃤 ",           -- Bug (nf-md-bug)
      Code = "󰅱 ",          -- Code (nf-md-code_braces)
      Telescope = "󰋷 ",     -- Telescope (nf-md-telescope)
      Gear = "󰢻 ",          -- Gear (nf-md-cog)
      Package = "󰏗 ",       -- Package (nf-md-package)
      List = "󰉻 ",          -- List (nf-md-format_list_bulleted)
      SignIn = "󰌆 ",        -- Sign-in (nf-md-login)
      SignOut = "󰍃 ",       -- Sign-out (nf-md-logout)
      NoteBook = "󰂺 ",      -- Notebook (nf-md-notebook)
      Check = "󰄬 ",         -- Check (nf-md-check)
      Fire = "󰝘 ",          -- Fire (nf-md-fire)
      Note = "󰎚 ",          -- Note (nf-md-note)
      BookMark = "󰃃 ",      -- Bookmark (nf-md-bookmark)
      Pencil = "󰏫 ",        -- Pencil (nf-md-pencil)
      ChevronRight = "󰅂 ",  -- Right chevron (nf-md-chevron_right)
      Table = "󰓫 ",         -- Table (nf-md-table_large)
      Calendar = "󰃵 ",      -- Calendar (nf-md-calendar)
      CloudDownload = "󰇚 ", -- Cloud arrow (nf-md-cloud_download)
    },
    diagnostics = {
      Error = "󰅙 ",         -- Error (nf-md-close_circle)
      Warning = "󰀪 ",       -- Warning (nf-md-alert)
      Information = "󰋽 ",   -- Info (nf-md-information)
      Question = "󰋗 ",      -- Question (nf-md-help_circle)
      Hint = "󰌵 ",          -- Hint (nf-md-lightbulb)
    },
    misc = {
      Robot = "󰚩 ",         -- Robot (nf-md-robot)
      Squirrel = "󰞗 ",      -- Squirrel (nf-md-squirrel)
      Tag = "󰓼 ",           -- Tag (nf-md-tag)
      Watch = "󰥔 ",         -- Watch (nf-md-watch)
      Smiley = "󰞆 ",        -- Smiley (nf-md-emoticon_happy)
      Package = "󰏗 ",       -- Package (nf-md-package)
      CircuitBoard = "󰆦 ",  -- Circuit (nf-md-circuit_board)
    },
  }
else
  -- Fallback branch with special characters and new folder symbols
  return {
    kind = {
      Text = "¶ ",          -- Paragraph symbol (text)
      Method = "λ ",        -- Greek lambda (method)
      Function = "ƒ ",      -- Function symbol
      Constructor = "⚒ ",   -- Hammer and pick (constructor)
      Field = "⊥ ",         -- Perpendicular (field)
      Variable = "α ",       -- Greek alpha (variable)
      Class = "© ",         -- Copyright (class)
      Interface = "ι ",      -- Greek iota (interface)
      Module = "□ ",        -- Square (module)
      Property = "π ",      -- Greek pi (property)
      Unit = "μ ",          -- Greek mu (unit)
      Value = "№ ",         -- Numero sign (value)
      Enum = "≡ ",          -- Triple bar (enum)
      Keyword = "κ ",       -- Greek kappa (keyword)
      Snippet = "✂ ",       -- Scissors (snippet)
      Color = "◉ ",         -- Bullseye (color)
      File = "φ ",          -- Greek phi (file)
      Reference = "↔ ",     -- Left-right arrow (reference)
      Folder = "⊼ ",        -- Small vee with underbar (closed folder)
      EnumMember = "∈ ",    -- Element of (enum member)
      Constant = "∞ ",      -- Infinity (constant)
      Struct = "⊞ ",        -- Window symbol (struct)
      Event = "⚡ ",        -- Lightning bolt (event)
      Operator = "+ ",      -- Plus (operator)
      TypeParameter = "τ ", -- Greek tau (type parameter)
    },
    git = {
      LineAdded = "+ ",      -- Plus (add)
      LineModified = "≈ ",   -- Almost equal (modified)
      LineRemoved = "- ",    -- Minus (remove)
      FileDeleted = "× ",    -- Multiplication (delete)
      FileIgnored = "∅ ",    -- Empty set (ignore)
      FileRenamed = "→ ",    -- Right arrow (rename)
      FileUnmerged = "≠ ",   -- Not equal (unmerged)
      FileUnstaged = "○ ",   -- Open circle (unstaged)
      FileStaged = "✔ ",     -- Checkmark (staged)
      FileUntracked = "? ",  -- Question mark (untracked)
      Diff = "∆ ",          -- Delta (diff)
      Repo = "ℝ ",          -- Real number symbol (repo)
      Octoface = "ϴ ",       -- Greek theta (octoface)
      Branch = "├ ",        -- Branch symbol
    },
    ui = {
      ArrowCircleDown = "↓ ",   -- Down arrow
      ArrowCircleLeft = "← ",   -- Left arrow
      Settings = "⚙ ",         -- Gear (settings)
      ArrowCircleRight = "→ ",  -- Right arrow
      ArrowCircleUp = "↑ ",     -- Up arrow
      BoldArrowDown = "▼ ",     -- Bold down
      BoldArrowLeft = "◄ ",     -- Bold left
      BoldArrowRight = "► ",    -- Bold right
      BoldArrowUp = "▲ ",       -- Bold up
      BoldClose = "✖ ",        -- Bold cross
      BoldDividerLeft = "[ ",   -- Left bracket
      BoldDividerRight = "] ",  -- Right bracket
      BoldLineLeft = "| ",      -- Vertical bar
      BookMark = "☆ ",         -- Star (bookmark)
      BoxChecked = "■ ",       -- Filled square (checked)
      Bug = "🐞 ",             -- Ladybug (bug)
      Stacks = "≡ ",           -- Triple bar (stacks)
      Scopes = "§ ",           -- Section (scopes)
      Watches = "⌚ ",          -- Watch
      DebugConsole = "» ",     -- Double right (console)
      Calendar = "📅 ",        -- Calendar
      Check = "✓ ",           -- Checkmark
      ChevronRight = "> ",     -- Right chevron
      ChevronShortDown = "v ",  -- Down chevron
      ChevronShortLeft = "< ",  -- Left chevron
      ChevronShortRight = "> ", -- Right chevron
      ChevronShortUp = "^ ",    -- Up chevron
      Circle = "○ ",           -- Open circle
      Close = "× ",           -- Cross
      CloudDownload = "↓☁ ",   -- Down arrow + cloud
      Code = "{}",            -- Braces (code)
      Comment = "# ",          -- Hash (comment)
      Dashboard = "◆ ",        -- Diamond (dashboard)
      DividerLeft = "( ",      -- Left paren
      DividerRight = ") ",     -- Right paren
      DoubleChevronRight = ">> ", -- Double right
      Ellipsis = "… ",         -- Ellipsis
      EmptyFolder = "⊼ ",      -- Small vee with underbar (closed folder)
      EmptyFolderOpen = "⋁ ",  -- N-ary logical or (open folder)
      File = "φ ",            -- Greek phi (file)
      FileSymlink = "↔ ",      -- Left-right arrow (symlink)
      Files = "¶¶ ",           -- Double paragraph (files)
      FindFile = "φ? ",        -- Phi + question (find file)
      FindText = "¶? ",        -- Paragraph + question (find text)
      Fire = "♨ ",            -- Hot springs (fire)
      Folder = "⊼ ",          -- Small vee with underbar (closed folder)
      FolderOpen = "⋁ ",      -- N-ary logical or (open folder)
      FolderSymlink = "⊼↔ ",   -- Closed folder + symlink
      Forward = "→ ",         -- Right arrow
      ArrowRight = "> ",      -- Right arrow
      Gear = "⚙ ",           -- Gear
      History = "◷ ",         -- Clockwise arrow (history)
      Lightbulb = "💡 ",      -- Bulb
      LineLeft = "| ",        -- Vertical bar
      LineMiddle = "│ ",      -- Light vertical bar
      List = "• ",            -- Bullet
      Lock = "🔒 ",          -- Lock
      NewFile = "+φ ",        -- Plus + phi (new file)
      Note = "♮ ",           -- Natural sign (note)
      Package = "□ ",        -- Square (package)
      Pencil = "✎ ",         -- Pencil
      Plus = "+ ",           -- Plus
      Project = "ℙ ",         -- Project (blackboard P)
      Search = "?",          -- Question mark (search)
      SignIn = "↳ ",         -- Down-right arrow (sign in)
      SignOut = "↱ ",        -- Up-right arrow (sign out)
      Tab = "— ",            -- Em dash (tab)
      Table = "⊞ ",          -- Window (table)
      Target = "◎ ",         -- Target
      Telescope = "🔭 ",     -- Telescope
      Text = "¶ ",           -- Paragraph (text)
      Tree = "♣ ",           -- Club (tree)
      Triangle = "△ ",       -- Triangle
      TriangleShortArrowDown = "v ", -- Down
      TriangleShortArrowLeft = "< ", -- Left
      TriangleShortArrowRight = "> ", -- Right
      TriangleShortArrowUp = "^ ", -- Up
    },
    diagnostics = {
      BoldError = "✘ ",       -- Bold cross (error)
      Error = "× ",          -- Cross (error)
      BoldWarning = "⚠ ",    -- Bold warning
      Warning = "!",         -- Exclamation (warning)
      BoldInformation = "ℹ ", -- Bold info
      Information = "i ",    -- Info
      BoldQuestion = "❓ ",   -- Bold question
      Question = "? ",       -- Question
      BoldHint = "💡 ",      -- Bold bulb (hint)
      Hint = "ℎ ",          -- Small h (hint)
      Debug = "🐞 ",         -- Ladybug (debug)
      Trace = "→ ",         -- Arrow (trace)
    },
    misc = {
      Robot = "🤖 ",         -- Robot emoji
      Squirrel = "ξ ",       -- Greek xi (squirrel-like)
      Tag = "🏷 ",          -- Tag emoji
      Watch = "⌚ ",         -- Watch
      Smiley = "☺ ",         -- Smiley
      Package = "□ ",        -- Square (package)
      CircuitBoard = "∿ ",   -- Sine wave (circuit)
    },
  }
end
